name: Unified Build Pipeline

on:
  workflow_dispatch:

jobs:
  set-build-number:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Increment Build Number
        run: |
          build_number=$(cat BUILD_NUMBER)
          build_number=$((build_number + 1))
          echo "$build_number" > BUILD_NUMBER
          git add BUILD_NUMBER
          git commit -m "trigger build $build_number"
          git push
        env:
          build_number: 0

  trigger-component-builds:
    runs-on: ubuntu-latest
    needs: set-build-number
    strategy:
      matrix:
        component: [component-a]
    steps:
      - name: Trigger Component Build
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/dieguscl/${{ matrix.component }}/actions/workflows/build.yml/dispatches \
          -d '{"ref": "main", "inputs": {"build_number": "$build_number"}}'

